FROM jenkins/jenkins:lts

# skip initial setup
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
# create default user
ENV JENKINS_USER admin
ENV JENKINS_PASS password
COPY default-user.groovy /usr/share/jenkins/ref/init.groovy.d/
# install plugins
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN jenkins-plugin-cli -f /usr/share/jenkins/plugins.txt
USER jenkins
