FROM jenkins/jenkins:lts
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/plugins.txt
USER root
RUN sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
USER jenkins